service: acm-mmm

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: us-east-1

  environment:
    EXECUTION_STAGE: ${self:provider.stage}
    AWS_DEPLOYMENT_REGION: ${self:provider.region}
    MONGODB_URI: ${file(./serverless-config/secrets.json):${self:provider.stage}.MONGODB_URI}


package:
  individually: true
  exclude:
   - ./**/*.md
   - .eslintrc.js
   - .prettierrc.js
   - .gitignore


functions:
  create-event:
    handler: src/routes/events/create.default

    events:
      - http:
          path: /events
          method: post
          cors: true

  get-events:
    handler: src/routes/events/get.default

    events:
      - http:
          path: /events
          method: get
          cors: true

  update-event:
    handler: src/routes/events/update.default

    events:
      - http:
          path: /events/{id}
          method: patch
          cors: true

  delete-event:
    handler: src/routes/events/delete.default

    events:
      - http:
          path: /events/{id}
          method: delete
          cors: true

  create-topic:
    handler: src/routes/topics/create.default

    events:
      - http:
          path: /topics
          method: post
          cors: true

  get-topics:
    handler: src/routes/topics/get.default

    events:
      - http:
          path: /topics
          method: get
          cors: true

  update-topic:
    handler: src/routes/topics/update.default

    events:
      - http:
          path: /topics/{id}
          method: patch
          cors: true

  delete-topics:
    handler: src/routes/topics/delete.default

    events:
      - http:
          path: /topics/{id}
          method: delete
          cors: true


custom:
  stages:
    - dev
    - v1.0

  serverless-offline:
    prefix: ${self:provider.stage}
    port: 3000
    stage: ${self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-stage-manager
  - serverless-webpack
  - serverless-offline
